# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-30 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brassiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bra_name', models.CharField(max_length=32)),
                ('bra_started_at', models.DateTimeField()),
                ('wash_num', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AddField(
            model_name='brassiere',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bras', to='login.User'),
        ),
    ]
